run:
  project_name: predict_methyl
  run_name: without_pretrain_drop_zero_atpm_methyl_DMR_allCT
  use_wandb: true
type: region
stage: fit
assembly: hg38
eval_tss: true
log_image: true
model:
  _target_: get_model.model.model.GETRegionFinetuneATAC
  cfg:
    num_regions: 200
    num_motif: 283
    embed_dim: 768
    num_layers: 12
    num_heads: 12
    dropout: 0.1
    output_dim: 1
    flash_attn: false
    pool_method: mean
    region_embed:
      num_regions: ${model.cfg.num_regions}
      num_features: ${model.cfg.num_motif}
      embed_dim: ${model.cfg.embed_dim}
    encoder:
      num_heads: ${model.cfg.num_heads}
      embed_dim: ${model.cfg.embed_dim}
      num_layers: ${model.cfg.num_layers}
      drop_path_rate: ${model.cfg.dropout}
      drop_rate: 0
      attn_drop_rate: 0
      use_mean_pooling: false
      flash_attn: ${model.cfg.flash_attn}
    head_exp:
      embed_dim: ${model.cfg.embed_dim}
      output_dim: 1
      use_atac: false
    mask_token:
      embed_dim: ${model.cfg.embed_dim}
      std: 0.02
    loss:
      components:
        atpm:
          _target_: torch.nn.PoissonNLLLoss
          reduction: mean
          log_input: false
      weights:
        atpm: 1.0
    metrics:
      components:
        atpm:
        - pearson
        - spearman
        - r2
machine:
  codebase: /home/alsun/miniforge3/envs/get/lib/python3.12/site-packages/get_model/
  data_path: /home/alsun/get/raw_data/
  output_dir: /home/alsun/get/2_methyl_model/output
  num_devices: 1
  num_workers: 2
  batch_size: 16
  fasta_path: ???
dataset:
  zarr_path: ./methyl_DMR.zarr
  celltypes: Astro-NT_NN,Astro-TE_NN,CA1-ProS_Glut,CA3_Glut,CB_Granule_Glut,CBX_Golgi_Gly-Gaba,CBX_Purkinje_Gaba,COAa-PAA-MEA_Barhl2_Glut,DG_Glut,IC_Tfap2d_Maf_Glut,IT_AON-TT-DP_Glut,IT_EP-CLA_Glut,L2_3_IT_CTX_Glut,L2_3_IT_ENT_Glut,L2_3_IT_PPP_Glut,L2_3_IT_RSP_Glut,L2_IT_ENT-po_Glut,L5_6_IT_TPE-ENT_Glut,L5_ET_CTX_Glut,L5_IT_CTX_Glut,L5_NP_CTX_Glut,L6b_CT_ENT_Glut,L6b_CTX_Glut,L6_CT_CTX_Glut,L6_IT_CTX_Glut,LA-BLA-BMA-PA_Glut,Lamp5_Gaba,LSX_Prdm12_Zeb2_Gaba,Microglia_NN,MY_Lhx1_Gly-Gaba,NDB-SI-MA-STRv_Lhx8_Gaba,Oligo_NN,OPC_NN,PB_Lmx1a_Glut,PG-TRN-LRN_Fat2_Glut,PRT_Tcf7l2_Gaba,Pvalb_Gaba,RT-ZI_Gnb3_Gaba,SCig_Foxb1_Glut,SCs_Dmbx1_Gaba,SI-MPO-LPO_Lhx8_Gaba,Sncg_Gaba,SNc-VTA-RAmb_Foxa1_Dopa,SPA-SPFm-SPFp-POL-PIL-PoT_Sp9_Glut,Sst_Gaba,STR_D1_Gaba,STR_D1_Sema5a_Gaba,STR_D2_Gaba,STR-PAL_Chst9_Gaba,SUB-ProS_Glut,TH_Prkcd_Grin2c_Glut,Vip_Gaba,VLMC_NN,ZI_Pax6_Gaba
  transform: null
  quantitative_atac: true
  sampling_step: 100
  num_region_per_sample: 200
  leave_out_chromosomes: chr10,chr11
  leave_out_celltypes: null
  mask_ratio: 0.0
training:
  save_ckpt_freq: 1
  epochs: 20
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false
  log_every_n_steps: 25
  val_check_interval: 1.0
  add_lr_monitor: false
  save_every_n_epochs: null
optimizer:
  lr: 0.0001
  min_lr: 0.0001
  weight_decay: 0.05
  opt: adamw
  opt_eps: 1.0e-08
  opt_betas:
  - 0.9
  - 0.999
finetune:
  resume_ckpt: null
  pretrain_checkpoint: false
  checkpoint: null
  strict: true
  model_key: model
  use_lora: false
  lora_checkpoint: null
  rename_config:
    blocks.: encoder.blocks.
    fc_norm.: encoder.norm.
    encoder.head.: head_mask.
    encoder.region_embed: region_embed
    region_embed.proj.: region_embed.embed.
    encoder.cls_token: cls_token
    head.: head_exp.head.
  layers_with_lora:
  - region_embed
  - encoder
  - head_exp
  patterns_to_freeze: []
  patterns_to_drop: []
  additional_checkpoints: []
task:
  test_mode: interpret
  gene_list: MYC,SOX10,SOX2,RET
  layer_names:
  - region_embed
  mutations: null
