name: Update Issue Start Dates in Project

on:
  workflow_dispatch:

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const projectNumber = 3;  // Change this
            const orgOrUser = 'asunboi';  // Change this
            
            // Get project info
            const projectQuery = `
              query($org: String!, $number: Int!) {
                user(login: $org) {
                  projectV2(number: $number) {
                    id
                    fields(first: 20) {
                      nodes {
                        ... on ProjectV2Field {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            const projectData = await github.graphql(projectQuery, {
              org: orgOrUser,
              number: projectNumber
            });
            
            const projectId = projectData.user.projectV2.id;
            const startDateField = projectData.user.projectV2.fields.nodes.find(f => f.name === 'Start Date');
            
            if (!startDateField) {
              throw new Error('Start Date field not found');
            }
            
            console.log(`Project ID: ${projectId}`);
            console.log(`Start Date Field ID: ${startDateField.id}`);
            
            // Get all issues
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            });
            
            console.log(`Found ${issues.length} issues`);
            
            for (const issue of issues) {
              const startDate = issue.created_at.split('T')[0];
              
              // Get project item for this issue
              const itemQuery = `
                query($owner: String!, $repo: String!, $issueNumber: Int!) {
                  repository(owner: $owner, name: $repo) {
                    issue(number: $issueNumber) {
                      projectItems(first: 10) {
                        nodes {
                          id
                          project {
                            id
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              const itemData = await github.graphql(itemQuery, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issueNumber: issue.number
              });
              
              const projectItem = itemData.repository.issue.projectItems.nodes.find(
                item => item.project.id === projectId
              );
              
              if (projectItem) {
                const updateMutation = `
                  mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: Date!) {
                    updateProjectV2ItemFieldValue(input: {
                      projectId: $projectId
                      itemId: $itemId
                      fieldId: $fieldId
                      value: { date: $value }
                    }) {
                      projectV2Item {
                        id
                      }
                    }
                  }
                `;
                
                await github.graphql(updateMutation, {
                  projectId: projectId,
                  itemId: projectItem.id,
                  fieldId: startDateField.id,
                  value: startDate
                });
                
                console.log(`✓ Updated #${issue.number} start date to ${startDate}`);
              }
            }
